---
title: "11/8 In-class Practice"
author: "Boxuan Li"
date: "11/8/2017"
output: html_document
---
### loading packages
```{r}
library(tidyverse)
library(readxl)
library(janitor)
theme_set(theme_bw())
theme_update(legend.position = "bottom")

set.seed(1)
```

### simple funtion
```{r computing z score}
x = rnorm(25)

mean(x)/sd(x)
```

### Build a function for this.
```{r building function for z score}
z_score <- function(x) {
  z = mean(x)/sd(x)
  
  z #return item (can also be writen as return(z))
}
```

```{r pluging the values into the function}
# Note that it has to be a vector indicating values to be pluged into the function.
z_score(runif(20,0,1))

# or

z_score(c(TRUE, TRUE, FALSE, TRUE))
```

### Add some control statement
```{r control statements}
z_score <- function(x) {
  
  if (!is.numeric(x)) {
    stop("x must be numeric!")
  } else if (length(x) < 3) {
    stop("x must have 3 or more entries")
  }
  z = mean(x)/sd(x)
  
  z
}
```

```{r}
z_score(rnorm(2))
```

### Output mean and sd as well
```{r adding output}
z_score <- function(x) {
  
  if (!is.numeric(x)) {
    stop("x must be numeric!")
  } else if (length(x) < 3) {
    stop("x must have 3 or more entries")
  }
  mean <- mean(x)
  sd <- sd(x)
  z <- mean/sd
  
  data_frame(mean,
             sd,
             z)
}
```

```{r}
z_score(rnorm(25))
```

### Simple linear regression 
```{r simple linear regression}
sim_data = tibble(
  x = runif(30),
  y = 2 + 3 * x + rnorm(30, 0, 1)
)

ggplot(sim_data, aes(x = x, y = y)) + 
  geom_point()

ls_fit = lm(y ~ x, data = sim_data)
  
beta0_hat = coef(ls_fit)[1]
beta1_hat = coef(ls_fit)[2]
```

### Build a funtion for the linear regression
```{r function for linear regression}
sim_regression <- function(n, beta0, beta1) {
  sim_data = tibble(
  x = runif(n),
  y = beta0 + beta1 * x + rnorm(n, 0, 1)
)

  ls_fit = lm(y ~ x, data = sim_data)
  
  tibble(
    beta0_hat = coef(ls_fit)[1],
    beta1_hat = coef(ls_fit)[2])
}
```

```{r plug values}
sim_regression(50,2,3)

sim_regression(2000,2,3)
```


### LoTR data
```{r}
fellowship_ring = read_excel("./data/LotR_Words.xlsx", range = "B3:D6") %>%
  clean_names() %>%
  gather(key = sex, value = words, female:male) %>%
  mutate(race = tolower(race),
         movie = "Fellowship")

two_towers = read_excel("./data/LotR_Words.xlsx", range = "F3:H6") %>%
  clean_names() %>%
  gather(key = sex, value = words, female:male) %>%
  mutate(race = tolower(race),
         movie = "Two Towers")

return_king = read_excel("./data/LotR_Words.xlsx", range = "J3:L6") %>%
  clean_names() %>%
  gather(key = sex, value = words, female:male) %>%
  mutate(race = tolower(race),
         movie = "Return")
```

### Build a function for the data extract
```{r building function to tidy dataset}
LoTR.data <- function(path, movie.name, cell_range) {
  df <- read_excel(path, range = cell_range) %>%
    clean_names() %>%
    gather(key = sex, value = words, female:male) %>%
    mutate(race = tolower(race),
         movie = movie.name)
  
  df
}

bind_rows(
  LoTR.data("./data/LotR_Words.xlsx", "Fellowship", "B3:D6"),
  LoTR.data("./data/LotR_Words.xlsx", "Two Towers", "F3:H6"),
  LoTR.data("./data/LotR_Words.xlsx", "Return", "J3:L6")
)
```

